# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.Main = QtWidgets.QWidget(Form)
        self.Main.setEnabled(True)
        self.Main.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Main.setAutoFillBackground(True)
        self.Main.setObjectName("Main")
        self.btn_stud_login = QtWidgets.QPushButton(self.Main)
        self.btn_stud_login.setGeometry(QtCore.QRect(60, 90, 100, 100))
        self.btn_stud_login.setObjectName("btn_stud_login")
        self.btn_prof_login = QtWidgets.QPushButton(self.Main)
        self.btn_prof_login.setGeometry(QtCore.QRect(190, 90, 100, 100))
        self.btn_prof_login.setObjectName("btn_prof_login")
        self.btn_3 = QtWidgets.QPushButton(self.Main)
        self.btn_3.setGeometry(QtCore.QRect(330, 90, 100, 100))
        self.btn_3.setObjectName("btn_3")
        self.Main_2 = QtWidgets.QWidget(Form)
        self.Main_2.setEnabled(True)
        self.Main_2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Main_2.setAutoFillBackground(True)
        self.Main_2.setObjectName("Main_2")
        self.line_number = QtWidgets.QLineEdit(self.Main_2)
        self.line_number.setGeometry(QtCore.QRect(110, 90, 251, 31))
        self.line_number.setInputMask("")
        self.line_number.setText("")
        self.line_number.setPlaceholderText("")
        self.line_number.setObjectName("line_number")
        self.line_last_name = QtWidgets.QLineEdit(self.Main_2)
        self.line_last_name.setGeometry(QtCore.QRect(110, 160, 251, 31))
        self.line_last_name.setObjectName("line_last_name")
        self.sign_in = QtWidgets.QPushButton(self.Main_2)
        self.sign_in.setGeometry(QtCore.QRect(200, 240, 80, 22))
        self.sign_in.setObjectName("sign_in")
        self.status = QtWidgets.QLabel(self.Main_2)
        self.status.setGeometry(QtCore.QRect(110, 210, 251, 20))
        self.status.setObjectName("status")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Main_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 280, 321, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.numerkKeyboard = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.numerkKeyboard.setContentsMargins(0, 0, 0, 0)
        self.numerkKeyboard.setSpacing(3)
        self.numerkKeyboard.setObjectName("numerkKeyboard")
        self.Main_3 = QtWidgets.QTabWidget(Form)
        self.Main_3.setGeometry(QtCore.QRect(0, 29, 800, 571))
        self.Main_3.setAutoFillBackground(True)
        self.Main_3.setObjectName("Main_3")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.Main_3.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.listView = QtWidgets.QListView(self.tab2)
        self.listView.setGeometry(QtCore.QRect(70, 10, 651, 441))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.tab2)
        self.pushButton.setGeometry(QtCore.QRect(350, 480, 80, 22))
        self.pushButton.setObjectName("pushButton")
        self.Main_3.addTab(self.tab2, "")
        self.btn_exit = QtWidgets.QPushButton(Form)
        self.btn_exit.setGeometry(QtCore.QRect(720, 10, 51, 41))
        self.btn_exit.setObjectName("btn_exit")
        self.Main_4 = QtWidgets.QWidget(Form)
        self.Main_4.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Main_4.setAutoFillBackground(True)
        self.Main_4.setObjectName("Main_4")
        self.btn_exit_2 = QtWidgets.QPushButton(self.Main_4)
        self.btn_exit_2.setGeometry(QtCore.QRect(300, 190, 171, 41))
        self.btn_exit_2.setObjectName("btn_exit_2")
        self.btn_back = QtWidgets.QPushButton(self.Main_4)
        self.btn_back.setGeometry(QtCore.QRect(300, 270, 171, 61))
        self.btn_back.setObjectName("btn_back")
        self.Splash = QtWidgets.QWidget(Form)
        self.Splash.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Splash.setAutoFillBackground(True)
        self.Splash.setObjectName("Splash")
        self.label = QtWidgets.QLabel(self.Splash)
        self.label.setGeometry(QtCore.QRect(300, 210, 221, 161))
        self.label.setObjectName("label")
        self.Main_5 = QtWidgets.QWidget(Form)
        self.Main_5.setEnabled(True)
        self.Main_5.setGeometry(QtCore.QRect(0, 10, 800, 600))
        self.Main_5.setAutoFillBackground(True)
        self.Main_5.setObjectName("Main_5")
        self.line_file_code = QtWidgets.QLineEdit(self.Main_5)
        self.line_file_code.setGeometry(QtCore.QRect(110, 90, 251, 31))
        self.line_file_code.setInputMask("")
        self.line_file_code.setText("")
        self.line_file_code.setPlaceholderText("")
        self.line_file_code.setObjectName("line_file_code")
        self.btn_print = QtWidgets.QPushButton(self.Main_5)
        self.btn_print.setGeometry(QtCore.QRect(200, 240, 80, 22))
        self.btn_print.setObjectName("btn_print")
        self.status_2 = QtWidgets.QLabel(self.Main_5)
        self.status_2.setGeometry(QtCore.QRect(110, 210, 251, 20))
        self.status_2.setObjectName("status_2")
        self.Main.raise_()
        self.Main_2.raise_()
        self.Main_3.raise_()
        self.Main_4.raise_()
        self.Main_5.raise_()
        self.btn_exit.raise_()
        self.Splash.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_stud_login.setText(_translate("Form", "styd"))
        self.btn_prof_login.setText(_translate("Form", "prof"))
        self.btn_3.setText(_translate("Form", "key_id"))
        self.line_last_name.setPlaceholderText(_translate("Form", "Last name"))
        self.sign_in.setText(_translate("Form", "sign in"))
        self.status.setText(_translate("Form", "TextLabel"))
        self.Main_3.setTabText(self.Main_3.indexOf(self.tab1), _translate("Form", "Tab 1"))
        self.pushButton.setText(_translate("Form", "печать"))
        self.Main_3.setTabText(self.Main_3.indexOf(self.tab2), _translate("Form", "Tab 2"))
        self.btn_exit.setText(_translate("Form", "X"))
        self.btn_exit_2.setText(_translate("Form", "Выйти"))
        self.btn_back.setText(_translate("Form", "выбрать другой файл"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Не забывай свою флешку </span><span style=\" font-weight:600;\"><br/><br/>и хорошего тебе дня :)</span></p></body></html>"))
        self.btn_print.setText(_translate("Form", "print"))
        self.status_2.setText(_translate("Form", "TextLabel"))
